import Foundation
import Testing
@testable import TankbookCore

// P0.12a: canonicalization and signature verification for remote config
// (docs/CONFIG.md; backend/src/Tankbook.Api/Config/ConfigCanonicalizer.cs).
//
// The parity fixture was generated by the REAL C# canonicalizer plus the same
// BouncyCastle Ed25519 the server signs with - not by this implementation - so
// these tests can actually fail. A test whose expected value came from the code
// under test would prove nothing about cross-language agreement.
//
// CONVENTION IN THIS FILE: the source stays pure ASCII. Non-ASCII characters are
// built with `UnicodeScalar`, and JSON escape sequences are written as literal
// backslash text (Swift "\\u000B" is the six characters backslash-u-0-0-0-B).
// Typing real control characters into the source is how this file got mangled
// once already.

// MARK: - Repo layout

/// Repo root, located from this file's path so tests are cwd-independent.
/// <repo>/ios/Tests/TankbookCoreTests/ConfigCanonicalizationTests.swift -> <repo>
private let repoRoot: URL = {
    URL(fileURLWithPath: #filePath).standardizedFileURL
        .deletingLastPathComponent() // TankbookCoreTests
        .deletingLastPathComponent() // Tests
        .deletingLastPathComponent() // ios
        .deletingLastPathComponent() // repo root
}()

private let configFixtures: URL =
    repoRoot.appendingPathComponent("ios/Tests/TankbookCoreTests/Fixtures/config")

private func fixtureData(_ name: String) throws -> Data {
    try Data(contentsOf: configFixtures.appendingPathComponent(name))
}

private func fixtureText(_ name: String) throws -> String {
    let data = try fixtureData(name)
    return String(decoding: data, as: UTF8.self).trimmingCharacters(in: .whitespacesAndNewlines)
}

private func canonicalString(_ json: String) throws -> String {
    let bytes = try ConfigCanonicalizer.canonicalize(Data(json.utf8))
    return String(decoding: bytes, as: UTF8.self)
}

private func scalar(_ value: UInt32) -> String {
    String(UnicodeScalar(value)!)
}

// MARK: - Cross-language parity

/// The load-bearing test. Byte equality against output produced by the server's
/// own canonicalizer; everything else here is a detail of how we get there.
@Test func canonicalBytesMatchTheServerGeneratedFixture() throws {
    let document = try fixtureData("parity.document.json")
    let expected = try fixtureData("parity.canonical.json")

    let canonical = try ConfigCanonicalizer.canonicalize(document)

    #expect(canonical == expected)
    #expect(canonical.count == 788, "fixture is 788 bytes; got \(canonical.count)")
}

@Test func fixtureSignatureVerifiesAgainstTheFixtureKey() throws {
    let document = try fixtureData("parity.document.json")
    let verifier = ConfigSignatureVerifier(publicKeyBase64: try fixtureText("parity.publickey.b64"))

    #expect(verifier.isConfigured)
    #expect(verifier.isValid(signatureBase64: try fixtureText("parity.signature.b64"),
                             documentBytes: document))
}

/// Tampers a field the code actually reads: bumping `version` past the rollback
/// floor is exactly what an attacker would try.
@Test func tamperedDocumentFailsVerification() throws {
    let original = try fixtureData("parity.document.json")
    let verifier = ConfigSignatureVerifier(publicKeyBase64: try fixtureText("parity.publickey.b64"))
    let signature = try fixtureText("parity.signature.b64")

    // Sanity: it verifies before tampering, so the failure below is the tamper.
    #expect(verifier.isValid(signatureBase64: signature, documentBytes: original))

    let json = String(decoding: original, as: UTF8.self)
    let tampered = json.replacingOccurrences(of: "\"version\": 7", with: "\"version\": 8")
    #expect(tampered != json, "the tamper did not apply; fixture shape must have changed")

    #expect(!verifier.isValid(signatureBase64: signature, documentBytes: Data(tampered.utf8)))
}

@Test func tamperedSignatureFailsVerification() throws {
    let document = try fixtureData("parity.document.json")
    let verifier = ConfigSignatureVerifier(publicKeyBase64: try fixtureText("parity.publickey.b64"))

    let decoded = Data(base64Encoded: try fixtureText("parity.signature.b64"))
    let unwrapped = try #require(decoded)
    var signature = [UInt8](unwrapped)
    signature[0] ^= 0x01

    let canonical = try ConfigCanonicalizer.canonicalize(document)
    #expect(!verifier.isValid(signature: Data(signature), canonicalBytes: canonical))
}

@Test func wrongPublicKeyFailsVerification() throws {
    let document = try fixtureData("parity.document.json")
    // A different, structurally valid Ed25519 public key.
    let other = ConfigSignatureVerifier(publicKeyBase64: "Q83AI9ItX54QfRoGk0V9NdHRDrfSHHIRkvVvXeQGZdM=")

    #expect(other.isConfigured, "the alternate key must itself be valid, or this proves nothing")
    #expect(!other.isValid(signatureBase64: try fixtureText("parity.signature.b64"),
                           documentBytes: document))
}

/// Server migration 003 seeds config v1 with an EMPTY signature placeholder,
/// signed at startup by ConfigBaselineSeeder - so a client can genuinely observe
/// that transient unsigned state and must reject it.
@Test func emptyOrPlaceholderSignatureIsRejected() throws {
    let document = try fixtureData("parity.document.json")
    let verifier = ConfigSignatureVerifier(publicKeyBase64: try fixtureText("parity.publickey.b64"))

    #expect(!verifier.isValid(signatureBase64: "", documentBytes: document))
    #expect(!verifier.isValid(signatureBase64: "   ", documentBytes: document))
    #expect(!verifier.isValid(signatureBase64: "not-base64!!", documentBytes: document))
    // Right length, wrong content.
    #expect(!verifier.isValid(signatureBase64: Data(repeating: 0, count: 64).base64EncodedString(),
                              documentBytes: document))
}

@Test func malformedPublicKeyRejectsEverythingRatherThanCrashing() throws {
    let document = try fixtureData("parity.document.json")
    let broken = ConfigSignatureVerifier(publicKey: Data([0x01, 0x02, 0x03]))

    #expect(!broken.isConfigured)
    #expect(!broken.isValid(signatureBase64: try fixtureText("parity.signature.b64"),
                            documentBytes: document))
}

@Test func aMalformedDocumentFailsVerificationRatherThanThrowing() throws {
    let verifier = ConfigSignatureVerifier(publicKeyBase64: try fixtureText("parity.publickey.b64"))

    // Cannot be canonicalized at all, so it cannot verify - and must not throw
    // past the call site, because a bad cache falls back to bundled defaults.
    #expect(!verifier.isValid(signatureBase64: try fixtureText("parity.signature.b64"),
                              documentBytes: Data("{ truncated".utf8)))
}

// MARK: - Rule 5: number source tokens

/// Asserted on BYTES, not on parsed values. Parsing both sides would pass even
/// if the canonicalizer round-tripped every number through Double, which is the
/// exact defect this rule exists to prevent.
@Test func numberTokensAreEmittedVerbatim() throws {
    let json = """
    {"a":1e3,"b":0.75,"c":9007199254740993,"d":1.0,"e":-0,"f":1E+2,"g":0.1000,"h":-1.5e-8}
    """
    let canonical = try canonicalString(json)

    #expect(canonical.contains("\"a\":1e3"), "1e3 must not become 1000")
    #expect(canonical.contains("\"b\":0.75"))
    #expect(canonical.contains("\"c\":9007199254740993"), "integers above 2^53 must stay exact")
    #expect(canonical.contains("\"d\":1.0"), "1.0 must not become 1")
    #expect(canonical.contains("\"e\":-0"), "-0 must not become 0")
    #expect(canonical.contains("\"f\":1E+2"), "exponent case and sign are part of the token")
    #expect(canonical.contains("\"g\":0.1000"), "trailing zeroes are part of the token")
    #expect(canonical.contains("\"h\":-1.5e-8"))
}

/// The negative control for the test above: a Double round-trip really does
/// destroy these tokens, so those assertions are not vacuous.
@Test func doubleRoundTripWouldDestroyTheseTokens() throws {
    #expect(String(try #require(Double("1e3"))) != "1e3")
    #expect(String(try #require(Double("9007199254740993"))) != "9007199254740993")
    #expect(String(try #require(Double("1.0"))) != "1")
}

// MARK: - Rule 2: ordinal key ordering

@Test func objectKeysSortOrdinallyAtEveryLevel() throws {
    let json = """
    {"zebra":1,"Apple":2,"apple":3,"nested":{"z":1,"a":2,"M":3},"_underscore":4,"10":5,"2":6}
    """
    let canonical = try canonicalString(json)

    // Ordinal, so uppercase sorts before lowercase and "10" before "2".
    let expected = """
    {"10":5,"2":6,"Apple":2,"_underscore":4,"apple":3,"nested":{"M":3,"a":2,"z":1},"zebra":1}
    """
    #expect(canonical == expected)
}

/// Swift's default `<` on String is Unicode collation, which orders "a" before
/// "Z". Ordinal does not.
@Test func orderingIsOrdinalNotSwiftCollation() throws {
    let canonical = try canonicalString("{\"a\":1,\"Z\":2}")

    #expect(canonical == "{\"Z\":2,\"a\":1}")
    #expect(("a" < "Z") == false, "sanity: Swift collation orders these the other way")
}

/// UTF-16 ordinal and UTF-8 byte order genuinely disagree for supplementary-plane
/// keys, and the server compares UTF-16 code units. U+1D400 is `f0 9d 90 80` in
/// UTF-8 but `D835 DC00` in UTF-16, so it sorts BEFORE U+FF3A (`ef bc ba` /
/// `FF3A`) ordinally and AFTER it by UTF-8 bytes. Verified against
/// StringComparer.Ordinal, not assumed.
@Test func supplementaryPlaneKeysSortByUTF16NotUTF8() throws {
    let fullwidthZ = scalar(0xFF3A)
    let mathematicalA = scalar(0x1D400)

    let canonical = try canonicalString("{\"\(fullwidthZ)\":1,\"\(mathematicalA)\":2}")

    // The supplementary key is emitted as an escaped surrogate pair, so look for
    // that form rather than the raw character.
    let supplementaryEscape = "\\uD835\\uDC00"
    let supplementaryIndex = try #require(canonical.range(of: supplementaryEscape))
    let fullwidthIndex = try #require(canonical.range(of: fullwidthZ))

    #expect(supplementaryIndex.lowerBound < fullwidthIndex.lowerBound,
            "UTF-16 ordinal puts the supplementary-plane key first; UTF-8 byte order would not")
}

// MARK: - Rule 4: string escaping

/// Every clause here was measured against Utf8JsonWriter with
/// UnsafeRelaxedJsonEscaping. Four of them are NOT what the JSON spec alone would
/// suggest, and each would silently break every signature.
///
/// The input is already in canonical escape form, so a correct canonicalizer
/// reproduces it exactly - which makes this a whole-output equality rather than a
/// bag of `contains` checks that could each pass for the wrong reason.
@Test func stringEscapingMatchesTheServerEncoder() throws {
    let escapes = "\\u000B\\b\\t\\n\\f\\r\\\"\\\\/<>&'\\u007F\\u2028\\u2029"
    let json = "{\"s\":\"\(escapes)\"}"

    let canonical = try canonicalString(json)

    #expect(canonical == "{\"s\":\"\(escapes)\"}")
    // Spelled out, so a failure names the clause that broke:
    #expect(canonical.contains("\\u000B"), "U+000B escapes as \\u000B, never \\v")
    #expect(canonical.contains("\\u007F"), "DEL is escaped though JSON does not require it")
    #expect(canonical.contains("\\u2028") && canonical.contains("\\u2029"),
            "line/paragraph separators are escaped though legal raw in JSON")
    #expect(canonical.contains("/<>&'"), "forward slash and HTML-sensitive chars stay raw")
    #expect(!canonical.contains("\\u000b"), "hex digits are uppercase")
}

@Test func nonASCIIBMPTextIsEmittedRaw() throws {
    let cyrillic = "\(scalar(0x041F))\(scalar(0x043B))\(scalar(0x0430))\(scalar(0x043D))"
    let cjk = "\(scalar(0x4E2D))\(scalar(0x6587))"

    let canonical = try canonicalString("{\"ru\":\"\(cyrillic)\",\"cjk\":\"\(cjk)\"}")

    #expect(canonical.contains(cyrillic), "Cyrillic must not be escaped")
    #expect(canonical.contains(cjk), "3-byte UTF-8 must round-trip intact")
    #expect(!canonical.contains("\\u04"))
}

/// Non-BMP scalars are escaped as a UTF-16 surrogate pair rather than emitted as
/// raw UTF-8 - the least obvious of the four measured divergences.
@Test func nonBMPScalarsAreEscapedAsSurrogatePairs() throws {
    let emoji = scalar(0x1F600)

    let canonical = try canonicalString("{\"e\":\"\(emoji)\"}")

    #expect(canonical == "{\"e\":\"\\uD83D\\uDE00\"}")
    #expect(!canonical.contains(emoji), "the raw emoji must not survive into the output")
}

/// Escaped input and raw input for the same character must canonicalize
/// identically - otherwise two documents that mean the same thing produce
/// different signatures.
@Test func escapedAndRawInputConvergeOnTheSameBytes() throws {
    let raw = "\(scalar(0x0416))\(scalar(0x4E2D))"

    let fromEscape = try canonicalString("{\"k\":\"\\u0416\\u4E2D\"}")
    let fromRaw = try canonicalString("{\"k\":\"\(raw)\"}")

    #expect(fromEscape == fromRaw)
    #expect(fromRaw == "{\"k\":\"\(raw)\"}")
}

// MARK: - Rules 3 and 6: whitespace and arrays

@Test func insignificantWhitespaceIsRemovedAndArrayOrderPreserved() throws {
    let json = """
    {
        "list" : [ 3, 1, 2, { "b" : 1, "a" : 2 } ],
        "empty" : {} ,
        "emptyList" : []
    }
    """
    let canonical = try canonicalString(json)

    #expect(canonical == "{\"empty\":{},\"emptyList\":[],\"list\":[3,1,2,{\"a\":2,\"b\":1}]}")
}

// MARK: - Malformed input

@Test func truncatedDocumentThrows() {
    #expect(throws: ConfigCanonicalizationError.self) {
        _ = try ConfigCanonicalizer.canonicalize(Data("{\"a\":1".utf8))
    }
}

@Test func nonObjectRootIsRejected() {
    #expect(throws: ConfigCanonicalizationError.rootIsNotAnObject) {
        _ = try ConfigCanonicalizer.canonicalize(Data("[1,2,3]".utf8))
    }
    #expect(throws: ConfigCanonicalizationError.rootIsNotAnObject) {
        _ = try ConfigCanonicalizer.canonicalize(Data("\"just a string\"".utf8))
    }
}

@Test func trailingContentIsRejected() {
    #expect(throws: ConfigCanonicalizationError.self) {
        _ = try ConfigCanonicalizer.canonicalize(Data("{\"a\":1} trailing".utf8))
    }
}

@Test func depthBeyondTheLimitIsRejected() throws {
    // 64 is the limit, matching the server's JsonDocumentOptions.MaxDepth.
    let withinLimit = String(repeating: "{\"a\":", count: 63) + "1" + String(repeating: "}", count: 63)
    #expect(throws: Never.self) {
        _ = try ConfigCanonicalizer.canonicalize(Data(withinLimit.utf8))
    }

    let beyondLimit = String(repeating: "{\"a\":", count: 65) + "1" + String(repeating: "}", count: 65)
    #expect(throws: ConfigCanonicalizationError.depthExceeded(limit: 64)) {
        _ = try ConfigCanonicalizer.canonicalize(Data(beyondLimit.utf8))
    }
}

@Test func malformedNumbersAndEscapesAreRejected() {
    let cases = [
        "{\"a\":1.}",           // fraction with no digits
        "{\"a\":1e}",           // exponent with no digits
        "{\"a\":+1}",           // leading plus is not legal JSON
        "{\"a\":\"\\q\"}",      // unknown escape
        "{\"a\":\"\\u12\"}",    // short hex quad
        "{\"a\":\"\\uD83D\"}",  // unpaired high surrogate
        "{\"a\":\"\\uDE00\"}",  // unpaired low surrogate
    ]
    for json in cases {
        #expect(throws: ConfigCanonicalizationError.self, "should reject: \(json)") {
            _ = try ConfigCanonicalizer.canonicalize(Data(json.utf8))
        }
    }
}

@Test func rawControlCharacterInAStringIsRejected() {
    var bytes = Array("{\"a\":\"x\"}".utf8)
    bytes[6] = 0x01 // replace the x with a raw control character
    #expect(throws: ConfigCanonicalizationError.self) {
        _ = try ConfigCanonicalizer.canonicalize(Data(bytes))
    }
}

@Test func invalidUTF8IsRejected() {
    // 0xC3 starts a 2-byte sequence; 0x28 is not a continuation byte.
    let bytes: [UInt8] = Array("{\"a\":\"".utf8) + [0xC3, 0x28] + Array("\"}".utf8)
    #expect(throws: ConfigCanonicalizationError.self) {
        _ = try ConfigCanonicalizer.canonicalize(Data(bytes))
    }
}

// MARK: - Typed document

@Test func parityFixtureDecodesIntoTypedFields() throws {
    let document = try ConfigDocument.parse(try fixtureData("parity.document.json"))

    #expect(document.version == 7)
    #expect(document.apiBaseURL == URL(string: "https://api.tankbook.app"))
    #expect(document.tier2OnDeviceLLM)
    #expect(!document.tier3CloudFallback)
    #expect(document.ocrConfidenceThreshold == 0.75)
    #expect(document.minSchemaVersion == 1)
    #expect(document.referencePacks.rates == 12)
    #expect(document.referencePacks.catalog == 3)
    #expect(document.rolloutSalt == "s4lt-2026-08")
    #expect(document.llmQuota.onDeviceLLM == 250)
    // Served as `1e3`: a valid JSON Schema integer that a plain Int decode rejects.
    #expect(document.llmQuota.cloudFallback == 1000)
    #expect(document.maintenance?.severity == .info)
    #expect(document.flags["zTrailingFlag"]?.rolloutPercent == 10)
    #expect(document.flags["aLeadingFlag"]?.enabled == false)
}

/// The cache stores the document verbatim so a future build understands keys this
/// build does not - so the raw bytes must survive a decode untouched.
@Test func unknownKeysSurviveDecodeInTheRawBytes() throws {
    let raw = try fixtureData("parity.document.json")
    let document = try ConfigDocument.parse(raw)

    #expect(document.rawBytes == raw)

    let text = String(decoding: document.rawBytes, as: UTF8.self)
    #expect(text.contains("unknownFutureKey"))
    #expect(text.contains("9007199254740993"), "the oversized integer survives as text")
}

@Test func aDocumentMissingARequiredFieldIsRejected() throws {
    let raw = try fixtureData("parity.document.json")
    let withoutVersion = String(decoding: raw, as: UTF8.self)
        .replacingOccurrences(of: "\"version\": 7,", with: "")

    #expect(throws: (any Error).self) {
        _ = try ConfigDocument.parse(Data(withoutVersion.utf8))
    }
}

/// An out-of-enum severity degrades to `.info` rather than discarding the whole
/// document, which might carry an urgent kill switch.
@Test func unknownMaintenanceSeverityDegradesToInfo() throws {
    let raw = String(decoding: try fixtureData("parity.document.json"), as: UTF8.self)
        .replacingOccurrences(of: "\"severity\": \"info\"", with: "\"severity\": \"catastrophe\"")

    let document = try ConfigDocument.parse(Data(raw.utf8))

    #expect(document.maintenance?.severity == .info)
    #expect(document.tier3CloudFallback == false, "the rest of the document still applies")
}
