import Foundation

/// The RV.162 screen -> door-witness table, kept in its own file so
/// `ScreenRouteScanner` stays a readable pure function. One binding per row of
/// `docs/SCREENMAP.md`'s per-screen index. A witness is a literal fragment of a
/// production door, chosen so a DEBUG-wrapped door removes it: `Route.about` is
/// the `NavigationLink` in Settings, `return .serviceEntry` is the capture-mode
/// mapping, and so on. Every binding carries a note (checked by the guard), so
/// the table cannot degrade into a skip list.
extension ScreenRouteScanner {

    static let bindings: [Binding] = [
        Binding(screen: "Welcome",
                witnesses: ["WelcomeRootView {"],
                note: "The pre-data root; TabRoots mounts it while there is no vehicle and no session."),
        Binding(screen: "Sign in",
                witnesses: ["presentSheet(.signIn)"],
                note: "The shared tab-root header and Settings present the sign-in sheet."),
        Binding(screen: "Restoring",
                witnesses: ["RestoringView("],
                note: "The sign-in flow's data-restore step."),
        Binding(screen: "Restore from backup",
                witnesses: ["Route.restoreFromBackup"],
                note: "RV.260: both restore-failure screens and Settings' row beside Export open the local Tankbook-backup door."),
        Binding(screen: "Add car",
                witnesses: ["Route.addVehicle"],
                note: "Home's empty state, Trends and the Car switcher push Add car."),
        Binding(screen: "Home",
                witnesses: ["HomeRootView("],
                note: "The Log tab root."),
        Binding(screen: "Inbox",
                witnesses: ["Route.inbox"],
                note: "The bell on the shared tab-root header."),
        Binding(screen: "Capture",
                witnesses: ["= .capture"],
                note: "The centre capture button sets the current tab's modal."),
        Binding(screen: "Capture review",
                witnesses: ["CaptureReviewView("],
                note: "The full-screen cover over Capture after the shutter."),
        Binding(screen: "Confirm / Foreign / Mixed / Manual",
                witnesses: ["presentSheet(.confirmManual)"],
                note: "Home's primary Type it door and both empty states."),
        Binding(screen: "Tank level",
                witnesses: ["TankLevelSheet("],
                note: "Presented by the fill-up form's tank row and by Edit entry."),
        Binding(screen: "Service & expenses",
                witnesses: ["return .serviceEntry"],
                note: "Capture's Service mode and Home's Type it menu resolve the form to this sheet."),
        Binding(screen: "Expense entry",
                witnesses: ["return .expenseEntry"],
                note: "Capture's Expense mode and Home's Type it menu resolve the form to this sheet."),
        Binding(screen: "Edit entry",
                witnesses: ["Route.editEntry"],
                note: "Log rows, duplicate/conflict cards, the Inbox and Recently deleted."),
        Binding(screen: "Excluded entries",
                witnesses: ["return .excludedEntries"],
                note: "The N>1 excluded footnote on Home and Trends."),
        Binding(screen: "Attachment viewer",
                witnesses: ["AttachmentViewerView("],
                note: "The receipt photo chip on Edit entry."),
        Binding(screen: "Trends",
                witnesses: ["TrendsRootView("],
                note: "The Trends tab root."),
        Binding(screen: "Garage",
                witnesses: ["GarageRootView("],
                note: "The Garage tab root."),
        Binding(screen: "Vehicle detail",
                witnesses: ["Route.vehicleDetail"],
                note: "Garage rows, the Car switcher's archived row and the limit sheet."),
        Binding(screen: "Tire sets",
                witnesses: ["Route.tireSets"],
                note: "The Vehicle detail row."),
        Binding(screen: "Tire set form",
                witnesses: ["Route.tireSetForm"],
                note: "The Tire sets list's New/row door."),
        Binding(screen: "Stations",
                witnesses: ["Route.stations"],
                note: "The Garage tab root's Stations door (RV.150)."),
        Binding(screen: "Station settings",
                witnesses: ["Route.stationSettings"],
                note: "A Stations list row."),
        Binding(screen: "Parts shelf",
                witnesses: ["Route.partsShelf"],
                note: "The pushed Vehicle detail row PJ.25 added; the nested service-entry sheet is the other door."),
        Binding(screen: "Car switcher",
                witnesses: ["presentSheet(.carSwitcher)"],
                note: "Home's car card/chip."),
        Binding(screen: "Reminders",
                witnesses: ["Route.reminders"],
                note: "The Home banner and the Vehicle detail row - PJ.4's fix, the historical positive case."),
        Binding(screen: "Reminders, all cars",
                witnesses: ["Route.remindersAll"],
                note: "Home's Reminders row and the Garage car attention count."),
        Binding(screen: "Service reminder offer",
                witnesses: ["ServiceReminderOfferSheet("],
                note: "The tab root hosts the offer after a service/expense save (RV.77)."),
        Binding(screen: "Reminder form",
                witnesses: ["Route.reminderForm"],
                note: "The Reminders lists' New/row door."),
        Binding(screen: "Reminder complete",
                witnesses: ["ReminderCompleteSheet("],
                note: "The Reminders list and a notification action present it."),
        Binding(screen: "Anomaly dismiss",
                witnesses: ["AnomalyDismissalSheet("],
                note: "The Log's anomaly card Dismiss with reason."),
        Binding(screen: "Recently deleted",
                witnesses: ["Route.recentlyDeleted"],
                note: "Settings' Recently deleted row."),
        Binding(screen: "Settings",
                witnesses: ["Route.settings"],
                note: "The gear on every tab-root header."),
        Binding(screen: "Account & devices",
                witnesses: ["Route.accountDevices"],
                note: "Settings' account card when signed in."),
        Binding(screen: "About & feedback",
                witnesses: ["Route.about"],
                note: "Settings' About row."),
        Binding(screen: "Diagnostics preview",
                witnesses: ["DiagnosticsPreviewView("],
                note: "About's Attach diagnostics preview.")
    ]
}
