#!/usr/bin/env python3
"""Rebuild the task index in docs/TASKS.md from the rows in TASKS.md + TASKS-DONE.md.

The index is the only part of TASKS.md that is generated. It is rewritten in place
between the two marker comments, so a row added or ticked by hand is picked up by
re-running this - the rows themselves are always the source of truth.

Usage: python3 scripts/tasks-index.py [--check]
  --check exits 1 if the index is stale, for a pre-commit or CI gate.
"""
import re
import sys
from pathlib import Path

DOCS = Path(__file__).resolve().parent.parent / "docs"
OPEN_FILE = DOCS / "TASKS.md"
DONE_FILE = DOCS / "TASKS-DONE.md"
BEGIN = "<!-- BEGIN TASK INDEX (generated by scripts/tasks-index.py) -->"
END = "<!-- END TASK INDEX -->"

ROW = re.compile(r"^\|\s*\*\*\[(x|~|!|cut| )\]\*\*\s*([^|]+?)\s*\|\s*(.*)$")
LEAD_MARKER = re.compile(r"\*\*((?:DONE|SHIPPED|FIXED|CLOSED|CUT)[^*]*)\*\*\s*")


def title(body: str) -> str:
    """The row's headline: its first bold sentence, minus any DONE/SHIPPED marker."""
    cell = body.split("|")[0].strip()
    while True:
        marker = LEAD_MARKER.match(cell)
        if not marker:
            break
        cell = cell[marker.end():]
    bold = re.match(r"\*\*(.+?)\*\*", cell)
    text = bold.group(1) if bold else cell
    if len(text.strip(" .")) < 4:
        text = cell
    text = re.sub(r"`([^`]*)`", r"\1", text)
    text = re.sub(r"\*\*|\*|\[|\]", "", text)
    text = re.sub(r"\s+", " ", text).strip(" .,:;-")
    text = re.split(r"(?<=[a-z0-9\)])\.\s", text)[0]
    return text[:95].strip(" .,:;-") or "(untitled)"


def rows(path: Path, where: str):
    heading = ""
    for line in path.read_text(encoding="utf-8").split("\n"):
        if line.startswith("## "):
            heading = line[3:].strip()
        match = ROW.match(line)
        if match:
            # A few legacy rows carry a whole parenthetical in the ID cell; the
            # index shows the id itself and leaves the note in the row.
            ident = match.group(2).strip().split(" ")[0].strip("*")
            yield match.group(1), ident, title(match.group(3)), heading, where


def build() -> str:
    entries = list(rows(OPEN_FILE, "below")) + list(rows(DONE_FILE, "TASKS-DONE.md"))
    lines = [BEGIN, "", "| ID | Title | Status | Where |", "|---|---|---|---|"]
    for status, ident, text, heading, where in entries:
        lines.append(f"| {ident} | {text} | `[{status}]` | {where} · {heading} |")
    lines += ["", END]
    return "\n".join(lines)



# --- Triage-table status stamping -------------------------------------------
#
# The launch-triage and priority-queue tables name task ids in prose ("**PJ.8**
# rate backfill trigger"). They were hand-annotated when a row shipped, which
# means they were annotated for four rows and then never again - so the tables
# went on describing shipped work as outstanding, and a reader trusted them.
# Every id mentioned in such a row now carries the status its OWN row has.

TRIAGE_ROW = re.compile(r"^\|\s*(\d+)\s*\|")
ID_IN_PROSE = re.compile(r"(?<!\[)\*\*((?:[A-Z]{1,3}\d*\.)+\d+[a-z]?)\*\*")


def statuses() -> dict:
    """Every task id mapped to its real status marker."""
    found = {}
    for path in (OPEN_FILE, DONE_FILE):
        for line in path.read_text(encoding="utf-8").split("\n"):
            match = ROW.match(line)
            if match:
                found[match.group(2).strip().split(" ")[0].strip("*")] = match.group(1)
    return found


def stamp_triage(doc: str) -> str:
    """Prefix every id named in a numbered triage row with its own status."""
    known = statuses()
    out = []
    for line in doc.split("\n"):
        if TRIAGE_ROW.match(line) and not ROW.match(line):
            def mark(match):
                ident = match.group(1)
                status = known.get(ident)
                if status is None:
                    return match.group(0)
                return f"**[{status}] {ident}**"
            # Only the first cell after the number carries the task names.
            cells = line.split("|")
            if len(cells) > 2:
                cells[2] = ID_IN_PROSE.sub(mark, cells[2])
                line = "|".join(cells)
        out.append(line)
    return "\n".join(out)


def main() -> int:
    doc = OPEN_FILE.read_text(encoding="utf-8")
    start, finish = doc.index(BEGIN), doc.index(END) + len(END)
    updated = stamp_triage(doc[:start] + build() + doc[finish:])
    if "--check" in sys.argv:
        if updated != doc:
            print("docs/TASKS.md index is stale - run scripts/tasks-index.py", file=sys.stderr)
            return 1
        return 0
    OPEN_FILE.write_text(updated, encoding="utf-8")
    print(f"index rebuilt: {len(list(rows(OPEN_FILE, 'below')))} open, "
          f"{len(list(rows(DONE_FILE, 'done')))} closed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
