import Foundation

/// Canonical serialization of a remote config document (docs/CONFIG.md ->
/// "Guardrails on apiBaseUrl", signed payload).
///
/// The Ed25519 signature is computed over these bytes, so this file and
/// `backend/src/Tankbook.Api/Config/ConfigCanonicalizer.cs` MUST agree byte for
/// byte. A divergence on either side silently rejects every document, which the
/// client then treats as tampering - so the failure mode is a fleet-wide fall
/// back to bundled defaults, not a crash. The parity fixture in
/// `Tests/.../Fixtures/config/` is the regression guard: it was generated by the
/// C# implementation, not by this one.
///
/// The six rules, mirroring the C# doc comment:
///   1. The document is a single JSON object.
///   2. Object members are emitted in ordinal key order at EVERY nesting level.
///   3. Compact - no insignificant whitespace.
///   4. Strings in minimal escape form (see `appendCanonicalString`).
///   5. Numbers are emitted EXACTLY as their source token: "0.75" stays "0.75",
///      "1e3" stays "1e3", and an integer above 2^53 stays exact. Neither side
///      re-serializes from a parsed floating-point value - that is the one place
///      naive implementations diverge.
///   6. Array element order is preserved.
///
/// Deliberately NOT built on `JSONValue` (Sources/TankbookCore/Sync), even though
/// that type also keeps raw number tokens. Its serializer diverges from
/// `Utf8JsonWriter` + `UnsafeRelaxedJsonEscaping` in four ways that were measured
/// against the real server encoder, every one of which would break signatures:
/// lowercase `\uXXXX` hex, U+007F emitted raw, U+2028/U+2029 emitted raw, and
/// non-BMP scalars emitted as raw UTF-8 rather than escaped surrogate pairs.
/// It also sorts keys with Swift's `<`, which is Unicode collation, not ordinal.
public enum ConfigCanonicalizer {
    /// Maximum nesting depth, matching the server's `JsonDocumentOptions.MaxDepth`.
    public static let maxDepth = 64

    /// Returns the canonical UTF-8 bytes of `documentBytes`.
    ///
    /// - Parameter documentBytes: the document exactly as served. The client
    ///   canonicalizes the bytes it received, never a re-encoded form, which is
    ///   what makes rule 5 safe.
    public static func canonicalize(_ documentBytes: Data) throws -> Data {
        var parser = CanonicalParser(bytes: [UInt8](documentBytes))
        let value = try parser.parseDocument()
        var output: [UInt8] = []
        output.reserveCapacity(documentBytes.count)
        value.append(to: &output)
        return Data(output)
    }
}

/// Errors raised while canonicalizing a config document. A malformed document is
/// rejected whole (docs/CONFIG.md -> "Document level: all or nothing"); the
/// caller falls back to the layer beneath rather than partially applying.
public enum ConfigCanonicalizationError: Error, Equatable, Sendable {
    case unexpectedEnd
    case unexpectedCharacter(at: Int)
    case trailingCharacters(at: Int)
    case expectedColon(at: Int)
    case invalidNumber(at: Int)
    case invalidEscape(at: Int)
    case invalidUnicodeEscape(at: Int)
    case invalidUTF8(at: Int)
    case controlCharacterInString(at: Int)
    /// The root value was not a JSON object (rule 1).
    case rootIsNotAnObject
    case depthExceeded(limit: Int)
}

// MARK: - Tree

/// A lossless JSON tree for canonicalization.
///
/// Objects are an ARRAY of pairs, not a dictionary: duplicate keys are preserved
/// and emitted like the server's `EnumerateObject` does, rather than silently
/// collapsing to the last one.
private enum CanonicalJSON {
    case null
    case bool(Bool)
    /// The raw source token, per rule 5.
    case number(String)
    case string(String)
    case array([CanonicalJSON])
    case object([(key: String, value: CanonicalJSON)])

    func append(to bytes: inout [UInt8]) {
        switch self {
        case .null:
            bytes.append(contentsOf: Array("null".utf8))
        case .bool(let value):
            bytes.append(contentsOf: Array((value ? "true" : "false").utf8))
        case .number(let token):
            bytes.append(contentsOf: Array(token.utf8))
        case .string(let value):
            Self.appendCanonicalString(value, to: &bytes)
        case .array(let items):
            bytes.append(UInt8(ascii: "["))
            for (index, item) in items.enumerated() {
                if index > 0 { bytes.append(UInt8(ascii: ",")) }
                item.append(to: &bytes)
            }
            bytes.append(UInt8(ascii: "]"))
        case .object(let entries):
            bytes.append(UInt8(ascii: "{"))
            // Rule 2: ordinal key order. See `isOrdinallyBefore` for why this is
            // not Swift's `<` and not UTF-8 byte order.
            let sorted = entries.sorted { isOrdinallyBefore($0.key, $1.key) }
            for (index, entry) in sorted.enumerated() {
                if index > 0 { bytes.append(UInt8(ascii: ",")) }
                Self.appendCanonicalString(entry.key, to: &bytes)
                bytes.append(UInt8(ascii: ":"))
                entry.value.append(to: &bytes)
            }
            bytes.append(UInt8(ascii: "}"))
        }
    }

    /// Rule 4, matching `Utf8JsonWriter` + `JavaScriptEncoder.UnsafeRelaxedJsonEscaping`
    /// exactly. Every clause below was measured against the real .NET encoder
    /// rather than inferred from the JSON spec, because three of them are not
    /// what the spec alone would suggest:
    ///
    ///   - Short escapes for \b \t \n \f \r only. U+000B is ``, never `\v`.
    ///   - Other C0 controls as `\uXXXX` with UPPERCASE hex digits.
    ///   - U+007F (DEL) IS escaped, though JSON does not require it.
    ///   - U+2028 and U+2029 ARE escaped, though they are legal raw in JSON.
    ///   - Non-BMP scalars are escaped as a UTF-16 SURROGATE PAIR
    ///     (`😀`), not emitted as raw UTF-8.
    ///   - `/`, `<`, `>`, `&`, `'` stay raw - that is what "relaxed" means.
    ///   - Everything else, including Cyrillic and CJK, is raw UTF-8.
    private static func appendCanonicalString(_ string: String, to bytes: inout [UInt8]) {
        bytes.append(UInt8(ascii: "\""))
        for scalar in string.unicodeScalars {
            switch scalar.value {
            case 0x08: bytes.append(contentsOf: Array("\\b".utf8))
            case 0x09: bytes.append(contentsOf: Array("\\t".utf8))
            case 0x0A: bytes.append(contentsOf: Array("\\n".utf8))
            case 0x0C: bytes.append(contentsOf: Array("\\f".utf8))
            case 0x0D: bytes.append(contentsOf: Array("\\r".utf8))
            case 0x22: bytes.append(contentsOf: Array("\\\"".utf8))
            case 0x5C: bytes.append(contentsOf: Array("\\\\".utf8))
            case 0x00 ... 0x1F, 0x7F, 0x2028, 0x2029:
                appendUnicodeEscape(UInt16(scalar.value), to: &bytes)
            case 0x10000...:
                // UTF-16 surrogate pair, uppercase hex, as .NET emits.
                let offset = scalar.value - 0x10000
                appendUnicodeEscape(UInt16(0xD800 + (offset >> 10)), to: &bytes)
                appendUnicodeEscape(UInt16(0xDC00 + (offset & 0x3FF)), to: &bytes)
            default:
                bytes.append(contentsOf: Array(String(scalar).utf8))
            }
        }
        bytes.append(UInt8(ascii: "\""))
    }

    private static func appendUnicodeEscape(_ unit: UInt16, to bytes: inout [UInt8]) {
        let digits = Array("0123456789ABCDEF".utf8)
        bytes.append(UInt8(ascii: "\\"))
        bytes.append(UInt8(ascii: "u"))
        bytes.append(digits[Int((unit >> 12) & 0xF)])
        bytes.append(digits[Int((unit >> 8) & 0xF)])
        bytes.append(digits[Int((unit >> 4) & 0xF)])
        bytes.append(digits[Int(unit & 0xF)])
    }
}

/// Ordinal comparison over **UTF-16 code units**, which is what
/// `StringComparer.Ordinal` does on the server.
///
/// This is neither Swift's `<` (Unicode collation, which orders "a" before "Z")
/// nor UTF-8 byte order. UTF-8 byte order genuinely disagrees with UTF-16 ordinal
/// for supplementary-plane keys: U+1D400 encodes to `f0 9d 90 80` in UTF-8 but to
/// the surrogate pair `D835 DC00` in UTF-16, so against U+FF3A (`ef bc ba` /
/// `FF3A`) the two orderings are opposite. Measured, not assumed.
private func isOrdinallyBefore(_ lhs: String, _ rhs: String) -> Bool {
    var left = lhs.utf16.makeIterator()
    var right = rhs.utf16.makeIterator()
    while true {
        switch (left.next(), right.next()) {
        case (nil, nil): return false
        case (nil, _): return true
        case (_, nil): return false
        case (let leftUnit?, let rightUnit?):
            if leftUnit != rightUnit { return leftUnit < rightUnit }
        }
    }
}

// MARK: - Parser

/// Recursive-descent parser that keeps number tokens verbatim (rule 5) and
/// decodes strings strictly, so a malformed document is rejected rather than
/// silently canonicalized into something that will not verify.
private struct CanonicalParser {
    let bytes: [UInt8]
    var index = 0
    var depth = 0

    init(bytes: [UInt8]) {
        self.bytes = bytes
    }

    mutating func parseDocument() throws -> CanonicalJSON {
        skipWhitespace()
        guard index < bytes.count else { throw ConfigCanonicalizationError.unexpectedEnd }
        // Rule 1: the document is a single JSON object.
        guard bytes[index] == UInt8(ascii: "{") else { throw ConfigCanonicalizationError.rootIsNotAnObject }
        let value = try parseValue()
        skipWhitespace()
        guard index == bytes.count else {
            throw ConfigCanonicalizationError.trailingCharacters(at: index)
        }
        return value
    }

    private mutating func skipWhitespace() {
        while index < bytes.count {
            switch bytes[index] {
            case 0x20, 0x09, 0x0A, 0x0D: index += 1
            default: return
            }
        }
    }

    private mutating func parseValue() throws -> CanonicalJSON {
        skipWhitespace()
        guard index < bytes.count else { throw ConfigCanonicalizationError.unexpectedEnd }
        switch bytes[index] {
        case UInt8(ascii: "{"): return try parseObject()
        case UInt8(ascii: "["): return try parseArray()
        case UInt8(ascii: "\""): return .string(try parseString())
        case UInt8(ascii: "t"): return try parseLiteral("true", .bool(true))
        case UInt8(ascii: "f"): return try parseLiteral("false", .bool(false))
        case UInt8(ascii: "n"): return try parseLiteral("null", .null)
        case UInt8(ascii: "-"), UInt8(ascii: "0") ... UInt8(ascii: "9"): return try parseNumber()
        default: throw ConfigCanonicalizationError.unexpectedCharacter(at: index)
        }
    }

    private mutating func parseLiteral(_ literal: String, _ value: CanonicalJSON) throws -> CanonicalJSON {
        let literalBytes = Array(literal.utf8)
        guard index + literalBytes.count <= bytes.count else { throw ConfigCanonicalizationError.unexpectedEnd }
        for (offset, byte) in literalBytes.enumerated() where bytes[index + offset] != byte {
            throw ConfigCanonicalizationError.unexpectedCharacter(at: index)
        }
        index += literalBytes.count
        return value
    }

    private mutating func enterNesting() throws {
        depth += 1
        guard depth <= ConfigCanonicalizer.maxDepth else {
            throw ConfigCanonicalizationError.depthExceeded(limit: ConfigCanonicalizer.maxDepth)
        }
    }

    private mutating func parseObject() throws -> CanonicalJSON {
        try enterNesting()
        defer { depth -= 1 }
        index += 1
        var entries: [(key: String, value: CanonicalJSON)] = []
        skipWhitespace()
        if index < bytes.count, bytes[index] == UInt8(ascii: "}") {
            index += 1
            return .object(entries)
        }
        while true {
            skipWhitespace()
            guard index < bytes.count, bytes[index] == UInt8(ascii: "\"") else {
                throw ConfigCanonicalizationError.unexpectedCharacter(at: index)
            }
            let key = try parseString()
            skipWhitespace()
            guard index < bytes.count, bytes[index] == UInt8(ascii: ":") else {
                throw ConfigCanonicalizationError.expectedColon(at: index)
            }
            index += 1
            entries.append((key: key, value: try parseValue()))
            skipWhitespace()
            guard index < bytes.count else { throw ConfigCanonicalizationError.unexpectedEnd }
            switch bytes[index] {
            case UInt8(ascii: ","): index += 1
            case UInt8(ascii: "}"): index += 1; return .object(entries)
            default: throw ConfigCanonicalizationError.unexpectedCharacter(at: index)
            }
        }
    }

    private mutating func parseArray() throws -> CanonicalJSON {
        try enterNesting()
        defer { depth -= 1 }
        index += 1
        var items: [CanonicalJSON] = []
        skipWhitespace()
        if index < bytes.count, bytes[index] == UInt8(ascii: "]") {
            index += 1
            return .array(items)
        }
        while true {
            items.append(try parseValue())
            skipWhitespace()
            guard index < bytes.count else { throw ConfigCanonicalizationError.unexpectedEnd }
            switch bytes[index] {
            case UInt8(ascii: ","): index += 1
            case UInt8(ascii: "]"): index += 1; return .array(items)
            default: throw ConfigCanonicalizationError.unexpectedCharacter(at: index)
            }
        }
    }

    /// Decodes a JSON string into UTF-8 bytes, resolving escapes, then validates
    /// the result as UTF-8. Multi-byte sequences are copied verbatim after their
    /// continuation bytes are checked, so a 3- or 4-byte character cannot be
    /// silently mangled.
    private mutating func parseString() throws -> String {
        index += 1
        var decoded: [UInt8] = []
        while index < bytes.count {
            let byte = bytes[index]
            if byte == UInt8(ascii: "\"") {
                index += 1
                guard let string = String(bytes: decoded, encoding: .utf8) else {
                    throw ConfigCanonicalizationError.invalidUTF8(at: index)
                }
                return string
            }
            if byte == UInt8(ascii: "\\") {
                index += 1
                try appendEscape(to: &decoded)
                continue
            }
            if byte < 0x20 {
                throw ConfigCanonicalizationError.controlCharacterInString(at: index)
            }
            let width = Self.utf8SequenceWidth(byte)
            guard width > 0, index + width <= bytes.count else {
                throw ConfigCanonicalizationError.invalidUTF8(at: index)
            }
            for offset in 1 ..< width where (bytes[index + offset] & 0xC0) != 0x80 {
                throw ConfigCanonicalizationError.invalidUTF8(at: index)
            }
            decoded.append(contentsOf: bytes[index ..< index + width])
            index += width
        }
        throw ConfigCanonicalizationError.unexpectedEnd
    }

    /// Byte count of the UTF-8 sequence starting with `byte`, or 0 if it is not a
    /// legal lead byte.
    private static func utf8SequenceWidth(_ byte: UInt8) -> Int {
        switch byte {
        case 0x00 ... 0x7F: return 1
        case 0xC2 ... 0xDF: return 2
        case 0xE0 ... 0xEF: return 3
        case 0xF0 ... 0xF4: return 4
        default: return 0
        }
    }

    private mutating func appendEscape(to decoded: inout [UInt8]) throws {
        guard index < bytes.count else { throw ConfigCanonicalizationError.unexpectedEnd }
        let escape = bytes[index]
        index += 1
        switch escape {
        case UInt8(ascii: "\""): decoded.append(0x22)
        case UInt8(ascii: "\\"): decoded.append(0x5C)
        case UInt8(ascii: "/"): decoded.append(0x2F)
        case UInt8(ascii: "b"): decoded.append(0x08)
        case UInt8(ascii: "f"): decoded.append(0x0C)
        case UInt8(ascii: "n"): decoded.append(0x0A)
        case UInt8(ascii: "r"): decoded.append(0x0D)
        case UInt8(ascii: "t"): decoded.append(0x09)
        case UInt8(ascii: "u"): try appendUnicodeEscape(to: &decoded)
        default: throw ConfigCanonicalizationError.invalidEscape(at: index)
        }
    }

    private mutating func appendUnicodeEscape(to decoded: inout [UInt8]) throws {
        let start = index
        guard let unit = readHexQuad() else {
            throw ConfigCanonicalizationError.invalidUnicodeEscape(at: start)
        }
        if unit >= 0xD800, unit <= 0xDBFF {
            // High surrogate: a low surrogate must follow, or the escape is invalid.
            guard index + 6 <= bytes.count,
                  bytes[index] == UInt8(ascii: "\\"),
                  bytes[index + 1] == UInt8(ascii: "u") else {
                throw ConfigCanonicalizationError.invalidUnicodeEscape(at: start)
            }
            index += 2
            guard let low = readHexQuad(), low >= 0xDC00, low <= 0xDFFF else {
                throw ConfigCanonicalizationError.invalidUnicodeEscape(at: start)
            }
            let value = 0x10000 + (UInt32(unit - 0xD800) << 10) + UInt32(low - 0xDC00)
            guard let scalar = Unicode.Scalar(value) else {
                throw ConfigCanonicalizationError.invalidUnicodeEscape(at: start)
            }
            decoded.append(contentsOf: Array(String(scalar).utf8))
            return
        }
        // An unpaired low surrogate is not a legal scalar.
        guard let scalar = Unicode.Scalar(UInt32(unit)) else {
            throw ConfigCanonicalizationError.invalidUnicodeEscape(at: start)
        }
        decoded.append(contentsOf: Array(String(scalar).utf8))
    }

    private mutating func readHexQuad() -> UInt16? {
        guard index + 4 <= bytes.count else { return nil }
        var value: UInt16 = 0
        for offset in 0 ..< 4 {
            guard let digit = Self.hexDigit(bytes[index + offset]) else { return nil }
            value = value << 4 | UInt16(digit)
        }
        index += 4
        return value
    }

    private static func hexDigit(_ byte: UInt8) -> UInt8? {
        switch byte {
        case UInt8(ascii: "0") ... UInt8(ascii: "9"): return byte - UInt8(ascii: "0")
        case UInt8(ascii: "a") ... UInt8(ascii: "f"): return byte - UInt8(ascii: "a") + 10
        case UInt8(ascii: "A") ... UInt8(ascii: "F"): return byte - UInt8(ascii: "A") + 10
        default: return nil
        }
    }

    /// Rule 5: the token is captured as its source substring and never parsed
    /// into a numeric type, so `1e3` and integers above 2^53 survive exactly.
    private mutating func parseNumber() throws -> CanonicalJSON {
        let start = index
        if index < bytes.count, bytes[index] == UInt8(ascii: "-") { index += 1 }
        guard try consumeDigits() else { throw ConfigCanonicalizationError.invalidNumber(at: index) }
        if index < bytes.count, bytes[index] == UInt8(ascii: ".") {
            index += 1
            guard try consumeDigits() else { throw ConfigCanonicalizationError.invalidNumber(at: index) }
        }
        if index < bytes.count, bytes[index] | 0x20 == UInt8(ascii: "e") {
            index += 1
            if index < bytes.count, bytes[index] == UInt8(ascii: "+") || bytes[index] == UInt8(ascii: "-") {
                index += 1
            }
            guard try consumeDigits() else { throw ConfigCanonicalizationError.invalidNumber(at: index) }
        }
        guard let token = String(bytes: bytes[start ..< index], encoding: .utf8) else {
            throw ConfigCanonicalizationError.invalidNumber(at: start)
        }
        return .number(token)
    }

    private mutating func consumeDigits() throws -> Bool {
        let start = index
        while index < bytes.count, bytes[index] >= UInt8(ascii: "0"), bytes[index] <= UInt8(ascii: "9") {
            index += 1
        }
        return index > start
    }
}
